# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Veri Bilimi 101
  items:
    - label: 'Temeller: Problemi Anlama'
      link: '/usage/problemi_anlama'
    - label: 'Veriyi Anlama'
      link: '/usage/veriyi_anlama'
    - label: 'Veri Analizi'
      link: '/usage/veri_analizi'
    - label: 'Modelleme'
      link: '/usage/modelleme'
    - label: 'Değerlendirme'
      link: '/usage/degerlendirme'
    - label: 'Hayata Geçirme'
      link: '/usage/hayata_gecirme'
- label: Veri Bilimi 102
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/taniostamar/Kodluyoruz_v3_content
