# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Veri Bilimi 101
  items:
    - label: 'Temeller: Problemi Anlama'
      link: '/usage/creating-docs'
    - label: 'Veriyi Anlama'
      link: '/usage/navigation'
    - label: 'Veri Analizi'
      link: '/usage/shadowing'
    - label: 'Modelleme'
      link: '/usage/shadowing'
    - label: 'Değerlendirme'
      link: '/usage/shadowing'
    - label: 'Hayata Geçirme'
      link: '/usage/shadowing'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/taniostamar/Kodluyoruz_v3_content
